export const SKILLS = [
    "React",
    "Next.js",
    "Tailwind CSS",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Git",
    "GitHub",
    "Docker",
    "Kubernetes",
    "AWS",
    "SQL",
    "NoSQL",
    "GCP",
    "CI/CD",
    "DevOps",
    "Cloud Computing",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Engineering",
    "Data Analysis",
    "Data Visualization",
    "Data Architecture",
    "Data Modeling",
    "Data Warehousing",
];